### ISSUE TITLE
StreamingEnabled Compatibility

### ISSUE THREAD

**Issue by lavender-sys** [headjoe3/Rocrastinate#2]
Currently Rocrastinate uses dot indexing in many of its internal files. This can potentially break games that have StreamingEnabled set to `true`.

**Comment by headjoe3** [comment]
Closing because of a previous discussion on discord—I am fairly sure StreamingEnabled does not apply to Non-BasePart instances, and static containers outside of the Workspace. Additionally, all of the contained instances are nested within the root ModuleScript, making this seem to be a moot point for non-static containers (static referring to those guaranteed to exist on the client when LocalScripts outside of ReplicatedFirst are run).
